import type { Metadata } from "next";
import "./globals.css";
import { MensagemProvider } from "@/data/contexts/MensagemContext";
import { ProvedorAutenticacao } from "@/data/contexts/ContextoAutenticacao";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <MensagemProvider>
        <ProvedorAutenticacao>
          <body>
            {children}
          </body>
        </ProvedorAutenticacao>
      </MensagemProvider>
    </html>
  );
}
